import { NextResponse } from "next/server";
import { signedUrl, isConfigured } from "@/lib/content/storage";

// Short-lived signed URLs for previewing generated assets. The bucket is
// private, so a generated still is never publicly addressable: the dashboard
// asks for a URL that expires.
export async function GET(request: Request): Promise<NextResponse> {
  const key = new URL(request.url).searchParams.get("key");
  if (!key) {
    return NextResponse.json({ status: "error", error: "key is required" }, { status: 400 });
  }
  // Keys are generated by lib/content/storage and always live under a known
  // prefix. Rejecting traversal keeps a crafted key from reaching another
  // bucket path.
  if (key.includes("..") || !/^(variants|avatars)\//.test(key)) {
    return NextResponse.json({ status: "error", error: "invalid key" }, { status: 400 });
  }
  if (!isConfigured()) {
    return NextResponse.json(
      { status: "awaiting_credentials", error: "object storage is not configured" },
      { status: 503 },
    );
  }
  try {
    const url = await signedUrl(key);
    return NextResponse.json({ status: "ok", data: { url } });
  } catch (err) {
    const message = err instanceof Error ? err.message : "unknown error";
    return NextResponse.json({ status: "error", error: message }, { status: 500 });
  }
}
